### signup request
POST http://127.0.0.1:5000/api/signup
content-type: application/json

{
    "email": "jia127",
    "password": "test"
}


### sign in request
POST http://127.0.0.1:5000/api/signin
content-type: application/json

{
    "email": "jia127",
    "password": "test"
}

### edit password request
POST http://127.0.0.1:5000/api/edit_password
content-type: application/json

{
    "email": "jia127",
    "old_password": "test",
    "new_password": "null"
}